export const ADMIN_NOTIFICATION_TYPES = [
  "JOB_COMPLETED",
  "CUSTOMER_REQUEST",
  "PAYMENT_RECEIVED",
  "MEMBERSHIP_PAYMENT_FAILED",
] as const;

export const CUSTOMER_NOTIFICATION_TYPES = [
  "JOB_COMPLETED",
  "SERVICE_SCHEDULED",
  "SERVICE_RESCHEDULED",
  "ROUTE_UPDATED",
  "INVOICE_SENT",
  "MEMBERSHIP_PAYMENT_FAILED",
] as const;

export const TECH_NOTIFICATION_TYPES = ["ROUTE_UPDATED"] as const;

export type AdminNotificationType = (typeof ADMIN_NOTIFICATION_TYPES)[number];
export type CustomerNotificationType =
  (typeof CUSTOMER_NOTIFICATION_TYPES)[number];
export type TechNotificationType = (typeof TECH_NOTIFICATION_TYPES)[number];

export const ROLE_NOTIFICATION_TYPES = {
  ADMIN: ADMIN_NOTIFICATION_TYPES,
  CUSTOMER: CUSTOMER_NOTIFICATION_TYPES,
  TECH: TECH_NOTIFICATION_TYPES,
} as const;
